# Generated by Django 5.1.2 on 2024-10-28 06:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("completed", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PR", "PROCCESSING"),
                            ("CM", "COMPLETED"),
                            ("CA", "CANCELLED"),
                        ],
                        default="PR",
                        max_length=2,
                    ),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        db_default=datetime.datetime(
                            2024,
                            10,
                            28,
                            6,
                            50,
                            14,
                            110710,
                            tzinfo=datetime.timezone.utc,
                        )
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="categories.category",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
