# Generated by Django 5.1.2 on 2024-10-25 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('PR', 'PROCCESSING'), ('CM', 'COMPLETED'), ('CA', 'CANCELLED')], default='PR', max_length=2),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(db_default=datetime.datetime(2024, 10, 25, 14, 45, 49, 686688, tzinfo=datetime.timezone.utc)),
        ),
    ]
