# Generated by Django 5.1.2 on 2024-10-28 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_alter_task_due_date_alter_task_project"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateTimeField(
                db_default=datetime.datetime(
                    2024, 10, 28, 11, 38, 36, 925541, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
