# Generated by Django 5.1.2 on 2024-10-31 10:47

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_alter_task_due_date_alter_task_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="percentage",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateTimeField(
                db_default=datetime.datetime(
                    2024, 10, 31, 10, 47, 56, 144730, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
