# Generated by Django 5.1.2 on 2024-11-06 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0001_initial"),
        ("tasks", "0005_task_percentage_alter_task_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateTimeField(
                db_default=datetime.datetime(
                    2024, 11, 6, 11, 24, 39, 199637, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tasks", to="tags.tag"
            ),
        ),
    ]
