# Generated by Django 5.1.2 on 2024-11-06 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_alter_task_due_date_alter_task_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateTimeField(
                db_default=datetime.datetime(
                    2024, 11, 6, 11, 57, 36, 906078, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
